forecast_date = "2025-05-13" # Date that the forecasts are actually submitted
reference_date = "2025-05-17" # Saturday following the forecast date
team_name = "epiforecasts"
model_name = "dyngam"
filepath_forecasts = "cityforecasts" # replace with "cityforecasts" for real submissions
model_filename = ["ar_mod", "ar_mod"]
locations_csv_path = "input/locations.csv"
targets = ["ILI ED visits", "Flu ED visits pct"]
pred_type = ["count", "pct"]
data_sources = "Hub target data"
data_url = ["https://raw.githubusercontent.com/reichlab/flu-metrocast/refs/heads/main/target-data/time-series.csv",
"https://raw.githubusercontent.com/reichlab/flu-metrocast/refs/heads/main/target-data/time-series.csv"]
data_format_type = ["target_data", "target_data"]
regions_to_fit = ["NYC", "TX"] # Specifies how to group locations for joint estimation
regions_to_target_mapping = ["NYC: ILI ED visits", "TX: flu ED visits pct"]
data_exclusion_period = ["2020-02-01", "2022-03-01"] # Don't fit to data within these dates
exclude_COVID = [true, true]
retrospective = [false, false]
input_data_path = "input/model_data"
forecast_horizon = [4, 4]
horizon_units = ["week", "week"]
timestep_data = ["week", "week"]
data_filename = ["NYC_weekly_counts", "TX_pct_flu_ED"]
for_submission = true # whether or not this forecast run will be submitted
[locs_list] # this isn't working yet but can use later
NYC= ["Bronx","Brooklyn","Manhattan", "NYC", "Queens", "Staten Island", "Unknown"]
TX = ["San Antonio", "Dallas", "El Paso","Houston","Austin"]
